stripe/stripe-payments-demo

public/index.html, public/javascripts/payments.js
- add redirect flow based payment method EPS: https://stripe.com/docs/sources/eps
- this is pretty much equivalent to Giropay, but only supports banks in Austria
=> add EPS payment method

public/javascripts/payments.js
Changes proposed in this pull request:
- WeChat Pay as a payment method in Japan
- Alipay as a payment method in Japan
=> Add WeChat Pay and Alipay as available payment methods in Japan

public/index.html, public/javascripts/payments.js, public/stylesheets/store.css
- adds ACH Credit Transfer payment method in single-use mode: https://stripe.com/docs/sources/ach-credit-transfer
- adds support for showing source creation error message
=> add single_use ACH credit transfer payment method

public/javascripts/payments.js
r? @romain-stripe 
In our Payment Request integration, we use `event.payerName` for the shipping recipient's name, even though we don't ask for `requestPayerName: true`. This results in `name` always being `null`.
Since the address is used for shipping, we should use `event.shippingAddress.recipient` instead.
=> Use shipping recipient's name in shipping address

server/node/inventory.js
Filter products by `type:good` to prevent interference with Stripe Billing products of type service introduced in API version 2018-02-05[0]
[0] https://stripe.com/docs/upgrades#2018-02-05
=> Filter products by type

server/python/requirements.txt
r? @adreyfus-stripe 
There's a security vulnerability in Flask 0.12.2 (https://nvd.nist.gov/vuln/detail/CVE-2018-1000656) that could allow a denial of service.  I *think* that this application is most likely not affected, as we don't invoke Flask's `json()` or `get_json()` directly, but it's probably best to update just in case there's a non-obvious code path that hits it.
=> server/python: update flask to 0.12.4

public/javascripts/payments.js
Fix to allow the correct postal code label to be displayed for United Kingdom.
=> Corrects abbreviation for United Kingdom

server/python/app.py
Added note that the templated strings need python 3.6 or later, fixed __name__ == "__main__", added hash-bang line so it could launch as a shell script, and added app.run() to launch it as a server (on port 5000 by default).
=> Update app.py so it can launch as a server

.env.example, README.md, public/index.html, public/javascripts/payments.js, public/javascripts/store.js, public/stylesheets/store.css, server/node/README.md, server/node/config.js, server/node/inventory.js, server/node/routes.js, server/node/server.js, server/node/setup.js, server/python/README.md, server/python/app.py, server/python/inventory.py, server/python/setup.py, server/python/stripe_types.py, server/python/tests/test_data.py, server/python/tests/tests.py
* Switch to PaymentIntents for all payment methods by confirming the PaymentIntent with a chargeable source.
* Remove all dependencies to the orders API.
* Upgrade to API version to 2019-02-11[0]
[0] https://stripe.com/docs/upgrades#2019-02-11
=> Change to PaymentIntents for all payment methods and upgrade to API version 2019-02-11

server/python/requirements.txt, server/python/tests/tests.py
Update `server/python/requirements.txt` for Jinja2 from 2.10 to 2.10.1.
Also, #48 added `shippingOptions` to the object returned by `/config`; this PR updates the Python tests accordingly.
r? @adreyfus-stripe || @thorsten-stripe
=> Python server: bump jinja2 and fix test

package.json, public/javascripts/store.js, server/node/inventory.js, server/node/routes.js, server/node/setup.js
closes #68 
* Make server/node/setup.js standalone script.
* Remove product exist checking which relies on hardcoded product names.
* Run product setup script on `postinstall` hook.
=> Decouple product setup.

README.md, app.yaml, package.json, server/node/README.md
Motivation: Google AppEngine is deprecating nodjs8 runtime.
=> Upgrade runtime to nodejs10.

README.md
`/server/java` -> `/server/go`
=> fix link to go example

package-lock.json, package.json
This value matches the documentation and silences warnings on environments with versions of environments higher than version 10.x
=> Update node engine to “>=10.x”

server/python/README.md, server/python/app.py
This PR adds a Flask route that allows .well-known files to be served.  Previously the missing route prevented the addition of web domains when configuring Apple Pay in the Stripe dashboard.
The PR also adds an explicit hint to readers to export FLASK_APP before running the app.
=> Add Flask route to serve .well-known files

.env.example, public/index.html, public/javascripts/payments.js, server/java/README.md, server/node/config.js, server/node/routes.js, server/php/settings.php
Per https://github.com/stripe/stripe-payments-demo/issues/142, adding Przelewy24 as a payment method.
cc. @thorsten-stripe @rgultiano-stripe 
* Added P24 availability to `.env.example`, Node and PHP configs
* Added P24 handler and config to `payments.js`
* Added error handling for `requires_payment_method` status, forward last error message
* Added 🇵🇱 to country selection, and P24 payment method to `index.html`
*P24 payment method selection*
*Authentication failure of P24 payment*
=> Adding Przelewy24 to Stripe Payments Demo

public/javascripts/payments.js
Fixes #142.
This PR moves Bancontact, EPS and Giropay away from their Sources integrations and into the PaymentIntents-based one.
- Moved iDEAL payment handler for consistency
- Added Bancontact, EPS and Giropay handlers that call their native Stripe.js methods
=> Migrate Bancontact, EPS and Giropay to PaymentIntents

public/javascripts/payments.js
A recent change stops users from display `metadata` for objects retrieved via publishable key. This repository passes around `metadata: { payment_intent: id }` on `Source` objects for polling purposes, which is now broken.
- Append `PaymentIntent` identifier to URL during `sourceData` creation
- No longer look up `PaymentIntent` during polling based on `metadata`
=> Fix polling via `Source` `metadata`

public/javascripts/payments.js
In #143, I broke `PaymentIntent` `status` polling for certain payment methods, like WeChat. A fellow developer filed #148 to report this.
More explicitly check if a `PaymentIntent` is in a terminal state by checking for `last_payment_error` in the back-end response.
=> Fix polling of `PaymentIntent` status

public/javascripts/payments.js
Per the [documentation](https://stripe.com/docs/payments/alipay/accept-a-payment), Alipay is now generally available on the `PaymentIntents` API, so this simply adds a handler to call `confirmAlipayPayment` via Stripe.js, rather than creating a `Source`.
- Add Alipay handler to `payments.js`
=> Move Alipay to PaymentIntents

README.md
It looks like the URLs for Stripe Elements docs have changed since those parts of this README were last updated, and some of the redirects don't point to the latest Stripe Elements docs (https://stripe.com/docs/elements now redirects to https://stripe.com/docs/payments/accept-a-payment-charges#web, which is not the newest API). 
I made the following changes:
* Updated the URL for general Stripe Elements info to https://stripe.com/payments/elements (could also theoretically point to https://stripe.com/docs/stripe-js#elements).
* Updated the URL for the Card Element to https://stripe.com/docs/stripe-js#card-element (which isn't that useful TBH). 
* Updated the URL for the Payment Request Button Element to https://stripe.com/docs/stripe-js/elements/payment-request-button …
=> Update URLs for Stripe Elements docs
